# Generated by Django 6.0.4 on 2026-04-10 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazardous', models.TextField(blank=True, null=True)),
                ('part', models.TextField()),
                ('item_code', models.TextField()),
                ('item_name', models.TextField()),
                ('lot_no', models.TextField(blank=True, null=True)),
                ('expiry_date', models.TextField(blank=True, null=True)),
                ('spec', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('reagent_type', models.TextField(blank=True, null=True)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('vendor', models.TextField(blank=True, null=True)),
                ('safety_stock', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField(default=0)),
                ('required_qty', models.IntegerField(default=0)),
                ('disposed_at', models.TextField(blank=True, null=True)),
                ('disposal_reason', models.TextField(blank=True, null=True)),
                ('disposal_type', models.TextField(blank=True, null=True)),
                ('opened_at', models.TextField(blank=True, null=True)),
                ('parallel_at', models.TextField(blank=True, null=True)),
                ('base_item_name', models.TextField(blank=True, null=True)),
                ('lot_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.TextField()),
                ('qty', models.IntegerField()),
                ('tx_date', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('remaining_stock', models.IntegerField(default=0)),
                ('item_code', models.TextField()),
                ('item_name', models.TextField()),
                ('lot_no', models.TextField(blank=True, null=True)),
                ('part', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'transaction_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
