# Generated by Django 6.0.4 on 2026-04-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('진단검사의학과', '진단검사의학과'), ('병리과', '병리과'), ('핵의학과', '핵의학과'), ('유해물질', '유해물질')], default='', max_length=50),
        ),
    ]
