# Generated by Django 6.0.4 on 2026-04-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_userprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='part',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
