# Generated by Django 6.0.4 on 2026-04-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_remove_userprofile_department_userprofile_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
