# Generated by Django 6.0.4 on 2026-04-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_userprofile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lab_part',
                'ordering': ['code'],
            },
        ),
    ]
