# Generated by Django 6.0.4 on 2026-04-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_part_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='schema_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('code', 'schema_name')},
        ),
    ]
