import os
import threading
from pathlib import Path

import psycopg

BASE_DIR = Path(__file__).resolve().parents[2]


def _load_dotenv(path: Path) -> None:
    """.env 파일이 있으면 읽어서, 아직 설정되지 않은 환경변수만 채워 넣는다.
    config/settings.py를 거치지 않고 이 모듈을 바로 쓰는 스크립트(예:
    fix_created_by.py)에서도 비밀번호를 읽을 수 있도록 여기서도 로드한다."""
    if not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


_load_dotenv(BASE_DIR / ".env")

PG_HOST = os.environ.get("REAGENT_PGHOST", "localhost")
PG_PORT = int(os.environ.get("REAGENT_PGPORT", "5432"))
PG_DBNAME = os.environ.get("REAGENT_PGDATABASE", "reagent")
PG_USER = os.environ.get("REAGENT_PGUSER", "postgres")
PG_PASSWORD = os.environ["REAGENT_PGPASSWORD"]

# Thread-local storage for the current department schema
_local = threading.local()

ALL_SCHEMAS = ("dlab", "path", "nm", "haz")


def set_schema(schema: str | None):
    """현재 스레드의 DB 스키마를 설정합니다."""
    _local.schema = schema


def get_current_schema() -> str | None:
    return getattr(_local, "schema", None)


class HybridRow(dict):
    def __init__(self, columns, values):
        super().__init__(zip(columns, values))
        self._values = tuple(values)

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return super().__getitem__(key)


def _normalize_query(query: str):
    return query.replace("?", "%s")


class CursorWrapper:
    def __init__(self, cursor):
        self._cursor = cursor
        self.description = None
        self.rowcount = -1

    def execute(self, query, params=None):
        query = _normalize_query(query) if isinstance(query, str) else query
        self._cursor.execute(query, params)
        self.description = self._cursor.description
        self.rowcount = self._cursor.rowcount
        return self

    def executemany(self, query, params_seq):
        query = _normalize_query(query) if isinstance(query, str) else query
        self._cursor.executemany(query, params_seq)
        self.description = self._cursor.description
        self.rowcount = self._cursor.rowcount
        return self

    def fetchone(self):
        row = self._cursor.fetchone()
        return self._wrap_row(row)

    def fetchall(self):
        rows = self._cursor.fetchall()
        return [self._wrap_row(row) for row in rows]

    def _wrap_row(self, row):
        if row is None or isinstance(row, dict):
            return row
        if isinstance(row, tuple) and self.description:
            columns = [col.name for col in self.description]
            return HybridRow(columns, row)
        return row

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class ConnectionWrapper:
    def __init__(self, connection):
        self._connection = connection

    def cursor(self):
        return CursorWrapper(self._connection.cursor())

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()

    def __getattr__(self, name):
        return getattr(self._connection, name)


def ensure_column(cursor, table_name, column_name, ddl):
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = %s
          AND column_name = %s
        """,
        (table_name, column_name),
    )
    if cursor.fetchone() is None:
        cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN {ddl}")


def get_connection():
    """현재 스레드에 설정된 스키마로 DB 연결을 반환합니다."""
    schema = get_current_schema()
    options_str = f"-c search_path={schema},public" if schema else None
    kwargs = dict(
        host=PG_HOST,
        port=PG_PORT,
        dbname=PG_DBNAME,
        user=PG_USER,
        password=PG_PASSWORD,
    )
    if options_str:
        kwargs["options"] = options_str
    conn = psycopg.connect(**kwargs)
    return ConnectionWrapper(conn)


def _init_schema_tables(schema: str):
    """특정 스키마에 inventory / transaction_history 테이블을 생성합니다."""
    # 직접 연결 (search_path 명시)
    conn = psycopg.connect(
        host=PG_HOST,
        port=PG_PORT,
        dbname=PG_DBNAME,
        user=PG_USER,
        password=PG_PASSWORD,
        options=f"-c search_path={schema},public",
    )
    wrapped = ConnectionWrapper(conn)
    cursor = wrapped.cursor()

    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {schema}.inventory (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            hazardous TEXT,
            part TEXT NOT NULL,
            item_code TEXT NOT NULL,
            item_name TEXT NOT NULL,
            lot_no TEXT,
            expiry_date TEXT,
            spec TEXT,
            unit TEXT,
            reagent_type TEXT,
            equipment TEXT,
            vendor TEXT,
            safety_stock INTEGER NOT NULL DEFAULT 0,
            current_stock INTEGER NOT NULL DEFAULT 0,
            required_qty INTEGER NOT NULL DEFAULT 0
        )
        """
    )

    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {schema}.transaction_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            inventory_id INTEGER NOT NULL REFERENCES {schema}.inventory(id),
            tx_type TEXT NOT NULL,
            qty INTEGER NOT NULL,
            tx_date TEXT NOT NULL,
            note TEXT NOT NULL DEFAULT '',
            remaining_stock INTEGER NOT NULL DEFAULT 0,
            item_code TEXT NOT NULL,
            item_name TEXT NOT NULL,
            lot_no TEXT,
            part TEXT,
            unit TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    # 추가 컬럼 (나중에 붙은 것들)
    ensure_column(cursor, "inventory", "disposed_at", "disposed_at TEXT")
    ensure_column(cursor, "inventory", "disposal_reason", "disposal_reason TEXT NOT NULL DEFAULT ''")
    ensure_column(cursor, "inventory", "disposal_type", "disposal_type TEXT NOT NULL DEFAULT ''")
    ensure_column(cursor, "inventory", "opened_at", "opened_at TEXT")
    ensure_column(cursor, "inventory", "parallel_at", "parallel_at TEXT")
    ensure_column(cursor, "inventory", "base_item_name", "base_item_name TEXT")
    ensure_column(cursor, "inventory", "lot_status", "lot_status TEXT NOT NULL DEFAULT ''")
    ensure_column(cursor, "inventory", "is_new_lot", "is_new_lot TEXT NOT NULL DEFAULT 'N'")
    ensure_column(cursor, "inventory", "registered_at", "registered_at TEXT")
    ensure_column(cursor, "transaction_history", "remaining_stock", "remaining_stock INTEGER NOT NULL DEFAULT 0")
    ensure_column(cursor, "transaction_history", "billing_type", "billing_type TEXT")
    ensure_column(cursor, "transaction_history", "created_by", "created_by TEXT NOT NULL DEFAULT ''")
    ensure_column(cursor, "transaction_history", "created_by_empno", "created_by_empno TEXT NOT NULL DEFAULT ''")

    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {schema}.barcode_units (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            inbound_tx_id INTEGER NOT NULL REFERENCES {schema}.transaction_history(id),
            inventory_id INTEGER NOT NULL REFERENCES {schema}.inventory(id),
            item_code TEXT NOT NULL,
            item_name TEXT NOT NULL,
            lot_no TEXT NOT NULL DEFAULT '',
            part TEXT NOT NULL DEFAULT '',
            unit TEXT NOT NULL DEFAULT '',
            serial_no INTEGER NOT NULL,
            qr_content TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            outbound_tx_id INTEGER REFERENCES {schema}.transaction_history(id),
            consumed_at TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    wrapped.commit()
    wrapped.close()


def init_all_schemas():
    """4개 부서 스키마를 생성하고 각각에 테이블을 초기화합니다."""
    # 스키마 생성은 superuser 연결로
    conn = psycopg.connect(
        host=PG_HOST,
        port=PG_PORT,
        dbname=PG_DBNAME,
        user=PG_USER,
        password=PG_PASSWORD,
    )
    cursor = conn.cursor()
    for schema in ALL_SCHEMAS:
        cursor.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
    conn.commit()
    conn.close()

    for schema in ALL_SCHEMAS:
        _init_schema_tables(schema)


def init_db():
    """(레거시) public 스키마에 테이블을 초기화합니다."""
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS inventory (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            hazardous TEXT,
            part TEXT NOT NULL,
            item_code TEXT NOT NULL,
            item_name TEXT NOT NULL,
            lot_no TEXT,
            expiry_date TEXT,
            spec TEXT,
            unit TEXT,
            reagent_type TEXT,
            equipment TEXT,
            vendor TEXT,
            safety_stock INTEGER NOT NULL DEFAULT 0,
            current_stock INTEGER NOT NULL DEFAULT 0,
            required_qty INTEGER NOT NULL DEFAULT 0
        )
        """
    )

    ensure_column(cursor, "inventory", "disposed_at", "disposed_at TEXT")
    ensure_column(cursor, "inventory", "disposal_reason", "disposal_reason TEXT NOT NULL DEFAULT ''")
    ensure_column(cursor, "inventory", "disposal_type", "disposal_type TEXT NOT NULL DEFAULT ''")
    ensure_column(cursor, "inventory", "opened_at", "opened_at TEXT")
    ensure_column(cursor, "inventory", "parallel_at", "parallel_at TEXT")
    ensure_column(cursor, "inventory", "base_item_name", "base_item_name TEXT")
    ensure_column(cursor, "inventory", "lot_status", "lot_status TEXT NOT NULL DEFAULT ''")
    ensure_column(cursor, "inventory", "is_new_lot", "is_new_lot TEXT NOT NULL DEFAULT 'N'")

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS transaction_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            inventory_id INTEGER NOT NULL REFERENCES inventory(id),
            tx_type TEXT NOT NULL,
            qty INTEGER NOT NULL,
            tx_date TEXT NOT NULL,
            note TEXT NOT NULL DEFAULT '',
            remaining_stock INTEGER NOT NULL DEFAULT 0,
            item_code TEXT NOT NULL,
            item_name TEXT NOT NULL,
            lot_no TEXT,
            part TEXT,
            unit TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    ensure_column(cursor, "transaction_history", "remaining_stock", "remaining_stock INTEGER NOT NULL DEFAULT 0")
    ensure_column(cursor, "transaction_history", "billing_type", "billing_type TEXT")
    ensure_column(cursor, "transaction_history", "created_by", "created_by TEXT NOT NULL DEFAULT ''")
    ensure_column(cursor, "transaction_history", "created_by_empno", "created_by_empno TEXT NOT NULL DEFAULT ''")

    conn.commit()
    conn.close()
